# PRs with these paths will be labeled with the following labels
dashboard:
  - changed-files:
    - any-glob-to-any-file: "apps/dashboard/**/*"
playground:
  - changed-files:
    - any-glob-to-any-file: "apps/playground-web/**/*"
packages:
  - changed-files:
    - any-glob-to-any-file: "packages/**/*"
portal:
  - changed-files:
    - any-glob-to-any-file: "apps/portal/**/*"
